version: '3.0'

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=sqs,sns
      - AWS_DEFAULT_REGION=eu-central-1
      - EDGE_PORT=4566
    ports:
      - '4566-4597:4566-4597'

  setup:
    image: amazon/aws-cli
    volumes:
      - "./setup_sqs_sns.sh:/setup_sqs_sns.sh"
    entrypoint: sh -c "/setup_sqs_sns.sh"
    depends_on:
      - localstack